### ISSUE TITLE
Looks like the build_[machinename].sh script is required

### ISSUE THREAD

**Issue by jchodera** [rmcgibbo/openmm-bench#1]
Without a `build_src.sh` script on `src`, I ran into:

```
+ source /home/jchodera/openmm-bench/openmm-bench.jchodera/conda-recipe/build_src.sh
/home/jchodera/openmm-bench/openmm-bench.jchodera/conda-recipe/build.sh: line 11: /home/jchodera/openmm-bench/openmm-bench.jchodera/conda-recipe/build_src.sh: No such file or directory
Command failed: /bin/bash -x -e /home/jchodera/openmm-bench/openmm-bench.jchodera/conda-recipe/build.sh
Traceback (most recent call last):
  File "/home/jchodera/miniconda/bin/asv", line 9, in <module>
    load_entry_point('asv==0.2.dev0-', 'console_scripts', 'asv')()
  File "/home/jchodera/miniconda/lib/python2.7/site-packages/asv-0.2.dev0_-py2.7.egg/asv/main.py", line 36, in main
    result = args.func(args)
  File "/home/jchodera/miniconda/lib/python2.7/site-packages/asv-0.2.dev0_-py2.7.egg/asv/commands/__init__.py", line 47, in run_from_args
    return cls.run_from_conf_args(conf, args)
  File "/home/jchodera/miniconda/lib/python2.7/site-packages/asv-0.2.dev0_-py2.7.egg/asv/commands/run.py", line 122, in run_from_conf_args
    skip_existing_commits=args.skip_existing_commits
  File "/home/jchodera/miniconda/lib/python2.7/site-packages/asv-0.2.dev0_-py2.7.egg/asv/commands/run.py", line 197, in run
    benchmarks = Benchmarks(conf, regex=bench)
  File "/home/jchodera/miniconda/lib/python2.7/site-packages/asv-0.2.dev0_-py2.7.egg/asv/benchmarks.py", line 285, in __init__
    for benchmark in benchmarks:
  File "/home/jchodera/miniconda/lib/python2.7/site-packages/asv-0.2.dev0_-py2.7.egg/asv/benchmarks.py", line 317, in disc_benchmarks
    env.install_project(conf)
  File "/home/jchodera/miniconda/lib/python2.7/site-packages/asv-0.2.dev0_-py2.7.egg/asv/plugins/conda.py", line 124, in install_project
    self, conf, commit_hash)
  File "/home/jchodera/miniconda/lib/python2.7/site-packages/asv-0.2.dev0_-py2.7.egg/asv/plugins/conda_cache.py", line 33, in build_project_cached
    fn = env.build_project(commit_hash)
  File "/home/jchodera/miniconda/lib/python2.7/site-packages/asv-0.2.dev0_-py2.7.egg/asv/plugins/conda.py", line 63, in build_project
    raise e
subprocess.CalledProcessError: Command '[u'/home/jchodera/miniconda/bin/conda-build', u'conda-recipe', u'--no-binstar-upload', u'--no-test', u'--python', u'3.4']' returned non-zero exit status 1
```

Once I created this file, it seems to be running fine.
The `README.md` may just need updating.

**Comment by rmcgibbo** [comment]
I think I tried to mention this in the README, but it still needs work. I'm still not totally sure how to properly crontab everything

**Comment by rmcgibbo** [comment]
FWIW, on @mpharrigan's machine, we set it up running in a separate account that with ssh keys that were associated with my @rmcgibbo-bot account, which I have as a "collaborator" on this repo, so that it can automatically push to master to update the results database (https://github.com/rmcgibbo/openmm-bench/tree/master/results, and the static html site, which is hosted in the gh-pages branch)

**Comment by jchodera** [comment]
`README` says:

> If you have OpenCL or CUDA installed in a nonstandard location, make a file inside the conda-recipes/ directory called build_.sh, and customize the flags that get passed to cmake

How about this?

Create a file inside the `conda-recipes/` directory called `build_[machinename].sh`, with `[machinename]` replaced with the name suggested when configuring `asv run` the first time.  If you have OpenCL or CUDA installed in a nonstandard location, use this to customize the flags that get passed to cmake, such as:

```
CMAKE_FLAGS+=" -DCUDA_TOOLKIT_ROOT_DIR=/home/harrigan/opt/cuda-6.5"
```

**Comment by rmcgibbo** [comment]
Sound good.

**Comment by rmcgibbo** [comment]
I will try to get this running on my windows dual boot. Should be an adventure...

**Comment by jchodera** [comment]
> FWIW, on @mpharrigan's machine, we set it up running in a separate account that with ssh keys that were associated with my @rmcgibbo-bot account

Is this still the easiest way to collect results if we're running this at multiple sites?

You'd just need our public SSH keys to add to @rmcgibbo-bot, right?

**Comment by jchodera** [comment]
Should we also distinguish driver version and GPU toolkit version used to compile?

**Comment by rmcgibbo** [comment]
It might be the easiest, yeah. In the mean time, if you want to just
collect the historical data, you can run 'asv run EXISTING' on your
machine, and then view the results with 'asv publish: asv preview', and
make a PR to merge your results file into the repo or something.

**Comment by rmcgibbo** [comment]
If you want, sure. Currently the code only runs one configuration per
'machine', and the GPU version string you enter is only used for displaying
the results.

**Comment by jchodera** [comment]
Hm, I must have screwed up my installation. The second time I ran it, it got caught up on 

```
· Creating environments......
```

but I'm not sure what it's actually doing there...

**Comment by jchodera** [comment]
Ah!  It was a conda lock problem.  `conda clean -l` cleared that up.

**Comment by rmcgibbo** [comment]
Ya, as you can probably tell, it's a bit.fo a hack job. It didn't
originally support conda-build, so I just kind of bolted it on.
